//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Studio.Web
{
	using System;
	using System.Data;
	using System.Xml;
	using System.Runtime.Serialization;
    
    
	[Serializable()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Diagnostics.DebuggerStepThrough()]
	[System.ComponentModel.ToolboxItem(true)]
	public class IconConfig : DataSet 
	{
        
		private IconDataTable tableIcon;
        
		public IconConfig() 
		{
			this.InitClass();
			System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			this.Tables.CollectionChanged += schemaChangedHandler;
			this.Relations.CollectionChanged += schemaChangedHandler;
		}
        
		protected IconConfig(SerializationInfo info, StreamingContext context) 
		{
			string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
			if ((strSchema != null)) 
			{
				DataSet ds = new DataSet();
				ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
				if ((ds.Tables["Icon"] != null)) 
				{
					this.Tables.Add(new IconDataTable(ds.Tables["Icon"]));
				}
				this.DataSetName = ds.DataSetName;
				this.Prefix = ds.Prefix;
				this.Namespace = ds.Namespace;
				this.Locale = ds.Locale;
				this.CaseSensitive = ds.CaseSensitive;
				this.EnforceConstraints = ds.EnforceConstraints;
				this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
				this.InitVars();
			}
			else 
			{
				this.InitClass();
			}
			this.GetSerializationData(info, context);
			System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			this.Tables.CollectionChanged += schemaChangedHandler;
			this.Relations.CollectionChanged += schemaChangedHandler;
		}
        
		[System.ComponentModel.Browsable(false)]
		[System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
		public IconDataTable Icon 
		{
			get 
			{
				return this.tableIcon;
			}
		}
        
		public override DataSet Clone() 
		{
			IconConfig cln = ((IconConfig)(base.Clone()));
			cln.InitVars();
			return cln;
		}
        
		protected override bool ShouldSerializeTables() 
		{
			return false;
		}
        
		protected override bool ShouldSerializeRelations() 
		{
			return false;
		}
        
		protected override void ReadXmlSerializable(XmlReader reader) 
		{
			this.Reset();
			DataSet ds = new DataSet();
			ds.ReadXml(reader);
			if ((ds.Tables["Icon"] != null)) 
			{
				this.Tables.Add(new IconDataTable(ds.Tables["Icon"]));
			}
			this.DataSetName = ds.DataSetName;
			this.Prefix = ds.Prefix;
			this.Namespace = ds.Namespace;
			this.Locale = ds.Locale;
			this.CaseSensitive = ds.CaseSensitive;
			this.EnforceConstraints = ds.EnforceConstraints;
			this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
			this.InitVars();
		}
        
		protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() 
		{
			System.IO.MemoryStream stream = new System.IO.MemoryStream();
			this.WriteXmlSchema(new XmlTextWriter(stream, null));
			stream.Position = 0;
			return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
		}
        
		internal void InitVars() 
		{
			this.tableIcon = ((IconDataTable)(this.Tables["Icon"]));
			if ((this.tableIcon != null)) 
			{
				this.tableIcon.InitVars();
			}
		}
        
		private void InitClass() 
		{
			this.DataSetName = "IconConfig";
			this.Prefix = "";
			this.Namespace = "http://FortuneAge.ControlLib/IconSchema.xsd";
			this.Locale = new System.Globalization.CultureInfo("en-US");
			this.CaseSensitive = false;
			this.EnforceConstraints = true;
			this.tableIcon = new IconDataTable();
			this.Tables.Add(this.tableIcon);
		}
        
		private bool ShouldSerializeIcon() 
		{
			return false;
		}
        
		private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) 
		{
			if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) 
			{
				this.InitVars();
			}
		}
        
		public delegate void IconRowChangeEventHandler(object sender, IconRowChangeEvent e);
        
		[System.Diagnostics.DebuggerStepThrough()]
			public class IconDataTable : DataTable, System.Collections.IEnumerable 
		{
            
			private DataColumn columnTag;
            
			private DataColumn columnName;
            
			private DataColumn columnFile;
            
			internal IconDataTable() : 
				base("Icon") 
			{
				this.InitClass();
			}
            
			internal IconDataTable(DataTable table) : 
				base(table.TableName) 
			{
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) 
				{
					this.CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) 
				{
					this.Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) 
				{
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
				this.DisplayExpression = table.DisplayExpression;
			}
            
			[System.ComponentModel.Browsable(false)]
			public int Count 
			{
				get 
				{
					return this.Rows.Count;
				}
			}
            
			internal DataColumn TagColumn 
			{
				get 
				{
					return this.columnTag;
				}
			}
            
			internal DataColumn NameColumn 
			{
				get 
				{
					return this.columnName;
				}
			}
            
			internal DataColumn FileColumn 
			{
				get 
				{
					return this.columnFile;
				}
			}
            
			public IconRow this[int index] 
			{
				get 
				{
					return ((IconRow)(this.Rows[index]));
				}
			}
            
			public event IconRowChangeEventHandler IconRowChanged;
            
			public event IconRowChangeEventHandler IconRowChanging;
            
			public event IconRowChangeEventHandler IconRowDeleted;
            
			public event IconRowChangeEventHandler IconRowDeleting;
            
			public void AddIconRow(IconRow row) 
			{
				this.Rows.Add(row);
			}
            
			public IconRow AddIconRow(string Tag, string Name, string File) 
			{
				IconRow rowIconRow = ((IconRow)(this.NewRow()));
				rowIconRow.ItemArray = new object[] {
														Tag,
														Name,
														File};
				this.Rows.Add(rowIconRow);
				return rowIconRow;
			}
            
			public System.Collections.IEnumerator GetEnumerator() 
			{
				return this.Rows.GetEnumerator();
			}
            
			public override DataTable Clone() 
			{
				IconDataTable cln = ((IconDataTable)(base.Clone()));
				cln.InitVars();
				return cln;
			}
            
			protected override DataTable CreateInstance() 
			{
				return new IconDataTable();
			}
            
			internal void InitVars() 
			{
				this.columnTag = this.Columns["Tag"];
				this.columnName = this.Columns["Name"];
				this.columnFile = this.Columns["File"];
			}
            
			private void InitClass() 
			{
				this.columnTag = new DataColumn("Tag", typeof(string), null, System.Data.MappingType.Attribute);
				this.Columns.Add(this.columnTag);
				this.columnName = new DataColumn("Name", typeof(string), null, System.Data.MappingType.Attribute);
				this.Columns.Add(this.columnName);
				this.columnFile = new DataColumn("File", typeof(string), null, System.Data.MappingType.Attribute);
				this.Columns.Add(this.columnFile);
				this.columnTag.Namespace = "";
				this.columnName.Namespace = "";
				this.columnFile.Namespace = "";
			}
            
			public IconRow NewIconRow() 
			{
				return ((IconRow)(this.NewRow()));
			}
            
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) 
			{
				return new IconRow(builder);
			}
            
			protected override System.Type GetRowType() 
			{
				return typeof(IconRow);
			}
            
			protected override void OnRowChanged(DataRowChangeEventArgs e) 
			{
				base.OnRowChanged(e);
				if ((this.IconRowChanged != null)) 
				{
					this.IconRowChanged(this, new IconRowChangeEvent(((IconRow)(e.Row)), e.Action));
				}
			}
            
			protected override void OnRowChanging(DataRowChangeEventArgs e) 
			{
				base.OnRowChanging(e);
				if ((this.IconRowChanging != null)) 
				{
					this.IconRowChanging(this, new IconRowChangeEvent(((IconRow)(e.Row)), e.Action));
				}
			}
            
			protected override void OnRowDeleted(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleted(e);
				if ((this.IconRowDeleted != null)) 
				{
					this.IconRowDeleted(this, new IconRowChangeEvent(((IconRow)(e.Row)), e.Action));
				}
			}
            
			protected override void OnRowDeleting(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleting(e);
				if ((this.IconRowDeleting != null)) 
				{
					this.IconRowDeleting(this, new IconRowChangeEvent(((IconRow)(e.Row)), e.Action));
				}
			}
            
			public void RemoveIconRow(IconRow row) 
			{
				this.Rows.Remove(row);
			}
		}
        
		[System.Diagnostics.DebuggerStepThrough()]
			public class IconRow : DataRow 
		{
            
			private IconDataTable tableIcon;
            
			internal IconRow(DataRowBuilder rb) : 
				base(rb) 
			{
				this.tableIcon = ((IconDataTable)(this.Table));
			}
            
			public string Tag 
			{
				get 
				{
					try 
					{
						return ((string)(this[this.tableIcon.TagColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
					}
				}
				set 
				{
					this[this.tableIcon.TagColumn] = value;
				}
			}
            
			public string Name 
			{
				get 
				{
					try 
					{
						return ((string)(this[this.tableIcon.NameColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
					}
				}
				set 
				{
					this[this.tableIcon.NameColumn] = value;
				}
			}
            
			public string File 
			{
				get 
				{
					try 
					{
						return ((string)(this[this.tableIcon.FileColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
					}
				}
				set 
				{
					this[this.tableIcon.FileColumn] = value;
				}
			}
            
			public bool IsTagNull() 
			{
				return this.IsNull(this.tableIcon.TagColumn);
			}
            
			public void SetTagNull() 
			{
				this[this.tableIcon.TagColumn] = System.Convert.DBNull;
			}
            
			public bool IsNameNull() 
			{
				return this.IsNull(this.tableIcon.NameColumn);
			}
            
			public void SetNameNull() 
			{
				this[this.tableIcon.NameColumn] = System.Convert.DBNull;
			}
            
			public bool IsFileNull() 
			{
				return this.IsNull(this.tableIcon.FileColumn);
			}
            
			public void SetFileNull() 
			{
				this[this.tableIcon.FileColumn] = System.Convert.DBNull;
			}
		}
        
		[System.Diagnostics.DebuggerStepThrough()]
			public class IconRowChangeEvent : EventArgs 
		{
            
			private IconRow eventRow;
            
			private DataRowAction eventAction;
            
			public IconRowChangeEvent(IconRow row, DataRowAction action) 
			{
				this.eventRow = row;
				this.eventAction = action;
			}
            
			public IconRow Row 
			{
				get 
				{
					return this.eventRow;
				}
			}
            
			public DataRowAction Action 
			{
				get 
				{
					return this.eventAction;
				}
			}
		}
	}
}
