using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using AnyWell.AW_DL;

public partial class Contorls_Regist_33 : UserControlBase
{
    protected void Page_Load( object sender, EventArgs e )
    {
       
    }

    private AW_Regist_bean _bean;
    public AW_Regist_bean bean
    {
        get
        {
            if( _bean == null )
            {
                _bean = ( AW_Regist_bean ) Context.Items[ "Context_Regist" ];
            }
            return _bean;
        }
        set
        {
            _bean = value;
        }
    }

    public string getCountry()
    {
        switch( bean.fdRegiCountry )
        {
            case 86:
                return "中国大陆";
            case 852:
                return "中国香港";
            case 853:
                return "中国澳门";
            case 886:
                return "中国台湾";
            case 93:
                return "阿富汗";
            case 355:
                return "阿尔巴尼亚";
            case 213:
                return "阿尔及利亚";
            case 376:
                return "安道尔";
            case 244:
                return "安哥拉";
            case 1264:
                return "安圭拉岛英";
            case 54:
                return "阿根廷";
            case 374:
                return "亚美尼亚";
            case 297:
                return "阿鲁巴岛";
            case 247:
                return "阿森松(英)";
            case 61:
                return "澳大利亚";
            case 43:
                return "奥地利";
            case 994:
                return "阿塞拜疆";
            case 1242:
                return "巴哈马";
            case 973:
                return "巴林";
            case 880:
                return "孟加拉国";
            case 1246:
                return "巴巴多斯";
            case 375:
                return "白俄罗斯";
            case 32:
                return "比利时";
            case 501:
                return "伯利兹";
            case 229:
                return "贝宁";
            case 1441:
                return "百慕大群岛";
            case 975:
                return "不丹";
            case 591:
                return "玻利维亚";
            case 387:
                return "波黑";
            case 267:
                return "博茨瓦纳";
            case 55:
                return "巴西";
            case 673:
                return "文莱";
            case 359:
                return "保加利亚";
            case 226:
                return "布基纳法索";
            case 95:
                return "缅甸";
            case 257:
                return "布隆迪";
            case 855:
                return "柬埔寨";
            case 237:
                return "喀麦隆";
            case 10:
                return "加拿大";
            case 238:
                return "佛得角";
            case 1345:
                return "开曼群岛";
            case 236:
                return "中非";
            case 235:
                return "乍得";
            case 56:
                return "智利";
            case 57:
                return "哥伦比亚";
            case 269:
                return "科摩罗";
            case 242:
                return "刚果";
            case 682:
                return "科克群岛";
            case 506:
                return "哥斯达黎加";
            case 385:
                return "克罗地亚";
            case 53:
                return "古巴";
            case 357:
                return "塞浦路斯";
            case 420:
                return "捷克";
            case 45:
                return "丹麦";
            case 253:
                return "吉布提";
            case 1767:
                return "多米尼加";
            case 1809:
                return "多米尼加共和国";
            case 593:
                return "厄瓜多尔";
            case 20:
                return "埃及";
            case 503:
                return "萨尔瓦多";
            case 240:
                return "赤道几内亚";
            case 291:
                return "厄立特里亚";
            case 372:
                return "爱沙尼亚";
            case 251:
                return "埃塞俄比亚";
            case 500:
                return "福克兰群岛";
            case 679:
                return "斐济";
            case 358:
                return "芬兰";
            case 33:
                return "法国";
            case 594:
                return "法属圭亚那";
            case 241:
                return "加蓬";
            case 220:
                return "冈比亚";
            case 995:
                return "格鲁吉亚";
            case 49:
                return "德国";
            case 233:
                return "加纳";
            case 350:
                return "直布罗陀";
            case 30:
                return "希腊";
            case 299:
                return "格陵兰岛";
            case 1473:
                return "格林纳达";
            case 1671:
                return "关岛";
            case 502:
                return "危地马拉";
            case 224:
                return "几内亚";
            case 245:
                return "几内亚比绍";
            case 592:
                return "圭亚那";
            case 509:
                return "海地";
            case 504:
                return "洪都拉斯";
            case 36:
                return "匈牙利";
            case 354:
                return "冰岛";
            case 91:
                return "印度";
            case 62:
                return "印度尼西亚";
            case 98:
                return "伊朗";
            case 964:
                return "伊拉克";
            case 353:
                return "爱尔兰";
            case 972:
                return "以色列";
            case 39:
                return "意大利";
            case 225:
                return "科特迪瓦";
            case 1876:
                return "牙买加";
            case 81:
                return "日本";
            case 962:
                return "约旦";
            case 7:
                return "哈萨克斯坦";
            case 254:
                return "肯尼亚";
            case 686:
                return "基里巴斯";
            case 82:
                return "韩国";
            case 965:
                return "科威特";
            case 996:
                return "吉尔吉斯坦";
            case 856:
                return "老挝";
            case 371:
                return "拉脱维亚";
            case 961:
                return "黎巴嫩";
            case 266:
                return "莱索托";
            case 231:
                return "利比里亚";
            case 218:
                return "利比亚";
            case 423:
                return "列支敦士登";
            case 370:
                return "立陶宛";
            case 352:
                return "卢森保";
            case 389:
                return "马其顿";
            case 261:
                return "马达加斯加";
            case 265:
                return "马拉维";
            case 60:
                return "马来西亚";
            case 960:
                return "马尔代夫";
            case 223:
                return "马里";
            case 356:
                return "马耳他";
            case 670:
                return "马里亚纳群岛";
            case 692:
                return "马绍尔群岛";
            case 596:
                return "马提尼克";
            case 222:
                return "毛里塔尼亚";
            case 230:
                return "毛里求斯";
            case 270:
                return "马约特岛";
            case 52:
                return "墨西哥";
            case 373:
                return "摩尔多瓦";
            case 377:
                return "摩纳哥";
            case 976:
                return "蒙古";
            case 1664:
                return "蒙特塞拉特岛";
            case 212:
                return "摩洛哥";
            case 258:
                return "莫桑比克";
            case 264:
                return "纳米比亚";
            case 674:
                return "瑙鲁";
            case 977:
                return "尼泊尔";
            case 31:
                return "荷兰";
            case 64:
                return "新西兰";
            case 505:
                return "尼加拉瓜";
            case 227:
                return "尼日尔";
            case 234:
                return "尼日利亚";
            case 683:
                return "纽埃岛(新)";
            case 672:
                return "诺福克岛";
            case 850:
                return "朝鲜";
            case 47:
                return "挪威";
            case 968:
                return "阿曼";
            case 92:
                return "巴基斯坦";
            case 507:
                return "巴拿马";
            case 675:
                return "巴布亚新几内亚";
            case 595:
                return "巴拉圭";
            case 51:
                return "秘鲁";
            case 63:
                return "菲律宾";
            case 48:
                return "波兰";
            case 351:
                return "葡萄牙";
            case 1787:
                return "波多黎各";
            case 974:
                return "卡塔尔";
            case 262:
                return "留尼汪岛";
            case 40:
                return "罗马尼亚";
            case 8:
                return "俄罗斯";
            case 250:
                return "卢旺达";
            case 685:
                return "萨摩亚";
            case 378:
                return "圣马力诺";
            case 966:
                return "沙特阿拉伯";
            case 221:
                return "塞内加尔";
            case 248:
                return "塞舌尔";
            case 232:
                return "塞拉利昂";
            case 65:
                return "新加坡";
            case 421:
                return "斯洛伐克";
            case 386:
                return "斯洛文尼亚";
            case 677:
                return "所罗门群岛";
            case 252:
                return "索马里";
            case 27:
                return "南非";
            case 34:
                return "西班牙";
            case 94:
                return "斯里兰卡";
            case 290:
                return "圣赫勒拿";
            case 1758:
                return "圣卢西亚";
            case 249:
                return "苏丹";
            case 597:
                return "苏里南";
            case 268:
                return "斯威士兰";
            case 46:
                return "瑞典";
            case 41:
                return "瑞士";
            case 963:
                return "叙利亚";
            case 255:
                return "坦桑尼亚";
            case 66:
                return "泰国";
            case 228:
                return "多哥";
            case 690:
                return "托克劳群岛(新)";
            case 676:
                return "汤加";
            case 216:
                return "突尼斯";
            case 90:
                return "土耳其";
            case 993:
                return "土库曼斯坦";
            case 688:
                return "图瓦卢";
            case 971:
                return "阿联酋";
            case 256:
                return "乌干达";
            case 380:
                return "乌克兰";
            case 44:
                return "英国";
            case 1:
                return "美国";
            case 598:
                return "乌拉圭";
            case 998:
                return "乌兹别克斯坦";
            case 678:
                return "瓦努阿图";
            case 379:
                return "梵蒂冈";
            case 58:
                return "委内瑞拉";
            case 84:
                return "越南";
            case 1808:
                return "威克岛(美)";
            case 967:
                return "也门";
            case 381:
                return "南斯拉夫";
            case 243:
                return "扎伊尔";
            case 260:
                return "赞比亚";
            case 263:
                return "津巴布韦";
            default:
                return "未知";
        }
    }
}
