tinyMCE.addI18n('en.importword_dlg',{
title:"Import word document",
imports:"Import",
html:"HTML format",
image:"Image format",
selectdoc:"Import document",
docpath:"Document",
method:"Import method",
replacesource:"Replace current code of editor",
better:"Better",
better_a:"选择优化模式(除以下选项外其他效果都被保留)",
better_a1:"Remove VML",
better_a2:"Remove float",
better_a3:"公式优化",
better_a4:"边距优化",
better_a5:"去除空行",
better_b:"全部清除模式(除以下选项外其他效果都被清除)",
better_b1:"保留图片",
better_b2:"表格优化",
better_b3:"公式优化",
better_b4:"首行缩进",
better_b5:"P转为BR",
better_c:"导入页面效果",
better_c1:"导入页宽",
better_c2:"页边距",
better_c3:"边框效果",
better_c4:"自动滚动",
better_img:"Image format",
better_warn:"Warning:All keys in document will be transfater into image, can't edit again"
});